name: Dev CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Backend
    - name: Build & Push Backend
      run: |
        docker build -t pavankamasani/devbackend ./backend
        docker push pavankamasani/devbackend

    # Frontend
    - name: Build & Push Frontend
      run: |
        docker build -t pavankamasani/devfrontend ./frontend
        docker push pavankamasani/devfrontend

    # Deploy
    - name: Deploy DEV
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull pavankamasani/devbackend
          docker pull pavankamasani/devfrontend

          docker rm -f dev-backend dev-frontend || true

          docker run -d -p 5001:5000 --name dev-backend pavankamasani/devbackend
          docker run -d -p 3001:80 --name dev-frontend pavankamasani/devfrontend
